// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fork-header/CenteredLockup.tsx": () => import("../components/mockups/fork-header/CenteredLockup.tsx"),
  "./components/mockups/fork-header/Current.tsx": () => import("../components/mockups/fork-header/Current.tsx"),
  "./components/mockups/fork-header/PersonalTerracotta.tsx": () => import("../components/mockups/fork-header/PersonalTerracotta.tsx"),
  "./components/mockups/fork-header/StampBadge.tsx": () => import("../components/mockups/fork-header/StampBadge.tsx")
};
